# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: plate_recognation.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'plate_recognation.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17plate_recognation.proto\x12\x05image\"1\n\x0cImageRequest\x12\r\n\x05token\x18\x01 \x01(\t\x12\x12\n\nimage_data\x18\x02 \x01(\x0c\"\x95\x01\n\rImageResponse\x12\x1c\n\x14license_plate_number\x18\x01 \x01(\t\x12\"\n\x1alicense_plate_number_score\x18\x02 \x01(\x02\x12\x1d\n\x15license_plate_country\x18\x03 \x01(\t\x12#\n\x1blicense_plate_country_score\x18\x04 \x01(\x02\x32S\n\x16ImageProcessingService\x12\x39\n\x0cProcessImage\x12\x13.image.ImageRequest\x1a\x14.image.ImageResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'plate_recognation_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_IMAGEREQUEST']._serialized_start=34
  _globals['_IMAGEREQUEST']._serialized_end=83
  _globals['_IMAGERESPONSE']._serialized_start=86
  _globals['_IMAGERESPONSE']._serialized_end=235
  _globals['_IMAGEPROCESSINGSERVICE']._serialized_start=237
  _globals['_IMAGEPROCESSINGSERVICE']._serialized_end=320
# @@protoc_insertion_point(module_scope)
